name    'bjoernalbers-homebrew'
version '0.0.1'
summary 'Homebrew package provider (batteries included)'
description 'Install Homebrew and manage Homebrew packages on Mac OS X.'
project_page 'https://github.com/bjoernalbers/puppet-homebrew'
license 'Apache License, Version 2.0'
author 'bjoernalbers'
